### ISSUE TITLE
Template Asks for AWS Account for Linux Engines

### ISSUE THREAD

**Issue by myhndl** [polyswarm/engine-template#2]
AWS accounts are currently required for Windows engines. They are not required for Linux engines. We shouldn't ask for AWS IDs when cutting a Linux-based engine.

**Comment by mrtizmoatwork** [comment]
You cannot omit questions with cookiecutter unless you have a wrapper around cookiecutter and you control every question yourself.

It's easier just to say "if using a linux engine, accept the default, it will be ignored."

**Comment by myhndl** [comment]
Dang, okay.

Ftr: https://github.com/audreyr/cookiecutter/issues/1021
